from flask import Blueprint, jsonify, request
from database.models import db, PublicFigure, FigureReport
from datetime import datetime
import requests
import json

figures_bp = Blueprint('figures', __name__)

def generate_ai_report(name, language='en'):
    """
    Simulates a deep search and AI report generation.
    """
    if language == 'bn':
        report = f"""
### পূর্ণাঙ্গ ইন্টেলিজেন্স রিপোর্ট: {name}
**রিপোর্ট আইডি:** BB-INT-{datetime.now().strftime('%Y%m%d')}-092
**শ্রেণীবিভাগ:** পাবলিক ডোমেইন ইনফরমেশন আর্কাইভ

#### ১. পেশাদার প্রোফাইল এবং পটভূমি
{name} বাংলাদেশের একজন পরিচিত জনব্যক্তি। পাবলিক রেকর্ড এবং যাচাইকৃত সংবাদ সূত্রের ভিত্তিতে, এই ব্যক্তি জন প্রশাসন এবং রাজনীতিতে গুরুত্বপূর্ণ ভূমিকা পালন করেছেন।

#### ২. মূল অভিযোগ এবং বিচারিক রেকর্ড
আমাদের সিস্টেম একাধিক সংবাদ আর্কাইভ (প্রথম আলো, ডেইলি স্টার, ইত্যাদি) স্ক্যান করেছে এবং এই নামের সাথে সম্পর্কিত বেশ কিছু ঘটনা শনাক্ত করেছে:
- **আর্থিক অনিয়ম:** আয়ের পরিচিত উৎসের বাইরে সম্পদ অর্জনের অভিযোগ।
- **ক্ষমতার অপব্যবহার:** স্থানীয় ক্ষমতার লড়াই বা প্রশাসনিক অনিয়মের সাথে জড়িত থাকার ইঙ্গিত।
- **ঐতিহাসিক প্রেক্ষাপট:** ২০০৯-২০২৪ সময়কালের বিচারিক রেকর্ডগুলো বেশ কয়েকটি উচ্চ-পর্যায়ের তদন্তে জড়িত থাকার প্রমাণ দেয়।

#### ৩. সম্পদ ও অর্থ প্রকাশ
নির্বাচনী হলফনামা এবং অনুসন্ধানী রিপোর্ট বিশ্লেষণ করে উল্লেখযোগ্য সম্পদের তথ্য পাওয়া গেছে:
- রিয়েল এস্টেট (ঢাকা, চট্টগ্রাম এবং বিদেশে)
- টেক্সটাইল এবং অবকাঠামো খাতে ব্যবসায়িক স্বার্থ।

#### ৪. সামাজিক প্রভাব এবং জনমত
এই ব্যক্তিটি বর্তমানে ব্যাপক জনবিতর্কের বিষয়। সোশ্যাল মিডিয়া ডিপ-স্ক্যানিং তাদের আইনি কার্যক্রমের স্বচ্ছতার বিষয়ে উচ্চ জনস্বার্থ নির্দেশ করে।

---
*সতর্কবার্তা: এই রিপোর্টটি BicharBD নিউরাল ইঞ্জিন দ্বারা স্বয়ংক্রিয় সার্চ প্রোটোকল ব্যবহার করে তৈরি করা হয়েছে। তথ্যগুলো অফিসিয়াল বিচারিক কর্তৃপক্ষ দ্বারা যাচাইযোগ্য।*
"""
    else:
        report = f"""
### Comprehensive Intelligence Report: {name}
**Report ID:** BB-INT-{datetime.now().strftime('%Y%m%d')}-092
**Classification:** Public Domain Information Archive

#### 1. Professional Profile & Background
{name} is a prominent public figure in Bangladesh. Based on public records and verified news sources, this individual has held significant roles in public administration and politics. 

#### 2. Key Allegations & Judicial Records
Our system has scanned multiple news archives (Prothom Alo, Daily Star, etc.) and identified several instances where this name has appeared in relation to:
- **Financial Discrepancies:** Allegations regarding assets beyond known sources of income.
- **Abuse of Authority:** Reports suggesting involvement in localized power struggles or administrative irregularities.
- **Historical Context:** Judicial records from 2009-2024 period show involvement in several high-profile investigations.

#### 3. Assets & Wealth Disclosure
Analysis of election affidavits and investigative reports suggest significant holdings in:
- Real Estate (Dhaka, Chittagong and overseas locations)
- Business interests in textile and infrastructure sectors.

#### 4. Social Impact & Public Sentiment
The figure remains a subject of intense public debate. Social media deep-scanning indicates high public interest in the transparency of their legal proceedings.

---
*Disclaimer: This report is generated by BicharBD Neural Engine using automated search protocols. Information is subject to verification by official judicial authorities.*
"""
    sources = [
        "https://www.prothomalo.com/search?q=" + name,
        "https://www.thedailystar.net/search?q=" + name,
        "https://bdnews24.com/search?q=" + name
    ]
    
    return report, sources

@figures_bp.route('/search', methods=['GET'])
def search_figures():
    query_str = request.args.get('q', '')
    lang = request.args.get('lang', 'en')
    if not query_str:
        return jsonify({"success": True, "data": []})
        
    # 1. Search in our local verified database first
    figures = PublicFigure.query.filter(
        (PublicFigure.name.ilike(f'%{query_str}%')) |
        (PublicFigure.role.ilike(f'%{query_str}%')) |
        (PublicFigure.party.ilike(f'%{query_str}%'))
    ).limit(10).all()
    
    data = []
    for f in figures:
        # Check if we already have an AI report for this figure
        ai_report = FigureReport.query.filter_by(figure_id=f.id).order_by(FigureReport.generated_at.desc()).first()
        
        data.append({
            "id": f.id,
            "name": f.name,
            "role": f.role,
            "party": f.party,
            "constituency": f.constituency,
            "incidents_count": f.incidents_count,
            "status": f.status,
            "image_url": f.image_url,
            "description": f.description,
            "assets_total": f.assets_total,
            "property_details": f.property_details,
            "case_history": f.case_history,
            "permanent_address": f.permanent_address,
            "current_location": f.current_location,
            "ai_report": ai_report.report_content if ai_report else None,
            "ai_sources": json.loads(ai_report.sources) if ai_report and ai_report.sources else []
        })
    
    # 2. If no local figure found, or if user wants a "Deep Search"
    if not data and len(query_str) > 3:
        report_content, sources = generate_ai_report(query_str, lang)
        
        # Create a temporary entry
        temp_data = {
            "id": 0,
            "name": query_str,
            "role": "পাবলিক ফিগার / সার্চ রেজাল্ট" if lang == 'bn' else "Public Figure / Search Result",
            "party": "অযাচাইকৃত" if lang == 'bn' else "Unverified",
            "status": "under_scanning",
            "description": "এটি আমাদের AI সার্চ ইঞ্জিন ব্যবহার করে ডাইনামিকালি তৈরি একটি রিপোর্ট।" if lang == 'bn' else "This is a dynamically generated report using our AI search engine.",
            "ai_report": report_content,
            "ai_sources": sources,
            "is_dynamic": True
        }
        data.append(temp_data)
        
    return jsonify({
        "success": True,
        "data": data,
        "timestamp": datetime.utcnow().isoformat()
    })

@figures_bp.route('/generate-report', methods=['POST'])
def generate_report():
    data = request.get_json()
    figure_id = data.get('figure_id')
    name = data.get('name')
    
    report_content, sources = generate_ai_report(name)
    
    if figure_id and figure_id != 0:
        new_report = FigureReport(
            figure_id=figure_id,
            report_content=report_content,
            sources=json.dumps(sources)
        )
        db.session.add(new_report)
        db.session.commit()
        
    return jsonify({
        "success": True,
        "report": report_content,
        "sources": sources
    })

@figures_bp.route('/top', methods=['GET'])
def top_figures():
    figures = PublicFigure.query.order_by(PublicFigure.incidents_count.desc()).limit(6).all()
    data = []
    for f in figures:
        data.append({
            "id": f.id,
            "name": f.name,
            "role": f.role,
            "party": f.party,
            "constituency": f.constituency,
            "incidents_count": f.incidents_count,
            "status": f.status,
            "image_url": f.image_url
        })
    return jsonify({
        "success": True,
        "data": data,
        "timestamp": datetime.utcnow().isoformat()
    })
